[lift]
name = "pbt"
description = """\
Python Build Tool: A BusyBox that provides `python`, `pip`, `pex`, `pex3` and `pex-tools`.\
"""

[lift.ptex]
version = "0.7.0"

[lift.scie-jump]
version = "0.11.1"

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20230507"
lazy = true
version = "3.8.16"

[[lift.files]]
name = "pex"
type = "blob"
digest = { size = 4085867, fingerprint = "82b24645769c19483c1306c1ba7a888471a5e1df3a2b538788bc7e0d1b20dbf0" }
source = { url = "https://github.com/pantsbuild/pex/releases/download/v2.1.134/pex" }

[[lift.commands]]
name = "pex"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[[lift.commands]]
name = "pex3"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[lift.commands.env.replace]
PEX_SCRIPT = "pex3"

[[lift.commands]]
name = "pex-tools"
exe = "#{cpython:python}"
args = [
    "{pex}"
]

[lift.commands.env.replace]
PEX_SCRIPT = "pex-tools"

[[lift.commands]]
name = "pip"
exe = "#{cpython:python}"
args = [
    "-m",
    "pip"
]

[[lift.commands]]
name = "python"
exe = "#{cpython:python}"
